export const icons = {
  tilde: '~',
  check: '✓',
  cross: '✗',
  warning: '⚠',
  info: 'ℹ',
  arrowUp: '↑',
  arrowDown: '↓',
  arrowLeft: '←',
  arrowRight: '→',
  ellipsis: '…',
  star: '★',
  branch: '⑂',
  edit: '✎',
  plus: '+',
  minus: '−',
  dot: '•',
  bullet: '▪',
  corner: '└',
  pipe: '│',
  diamond: '◆',
  circle: '●',
  square: '■',
  triangle: '▲',
  chevronLeft: '‹',
  chevronRight: '›',
  chevronUp: '˄',
  chevronDown: '˅',
  chevronDoubleLeft: '«',
  chevronDoubleRight: '»',
  chevronBoldRight: '❱',
  chevronBoldLeft: '❰',
  chevronHeavyRight: '❯',
  chevronHeavyLeft: '❮'
} as const;

export type IconName = keyof typeof icons;
